name: firebase_auth_oauth_web
description: Web implementation for `firebase_auth_oauth`.  Don't use directly. Instead import `firebase_auth_oauth` plugin.
version: 1.1.1
homepage: https://github.com/amrfarid140/firebase_auth_oauth/tree/master/firebase_auth_oauth_web

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^9.0.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_auth_oauth_platform_interface: ^1.0.3
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthOAuthWeb
        fileName: firebase_auth_oauth_web.dart
