name: firebase_auth_oauth
description: A Flutter plugin that makes it easy to perform OAuth sign in flows using FirebaseAuth. It also includes support for Sign in by Apple for Firebase.
version: 1.2.2
homepage: https://github.com/amrfarid140/firebase_auth_oauth/tree/master/firebase_auth_oauth

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_auth_oauth_platform_interface: ^1.0.3
  firebase_auth_oauth_web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.amryousef.apple.auth.firebase_auth_oauth
        pluginClass: FirebaseAuthOAuthPlugin
      ios:
        pluginClass: FirebaseAuthOAuthPlugin
      web:
        default_package: firebase_apple_auth_web

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/web/index.html
  - /example/lib/firebase_options.dart